---
apiVersion: v1
kind: Service
metadata:
  name: backend-c
spec:
  selector:
    app: backend-c
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-c
  labels:
    app: backend-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-c
  template:
    metadata:
      labels:
        app: backend-c
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      containers:
        - name: backend-c
          image: nicholasjackson/fake-service:v0.7.8
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            - name: 'NAME'
              value: 'backend-c'
            - name: 'MESSAGE'
              value: 'Response from backend-c'
