global:
  enabled: false
  name: consul
  peering:
    enabled: true
  adminPartitions:
    enabled: true
    name: ${partition_name}
  image: "hashicorp/consul-enterprise:${consul_version}"
  datacenter: ${deployment_name}
  tls:
    enabled: true
    enableAutoEncrypt: true
    caCert:
      secretName: ${deployment_name}-hcp
      secretKey: caCert
  enableConsulNamespaces: true
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: ${deployment_name}-bootstrap-token
      secretKey: token
  gossipEncryption:
    secretName: ${deployment_name}
    secretKey: gossipEncryptionKey
  metrics:
    enabled: true
externalServers:
  enabled: true
  hosts: ['${server_private_fqdn}']
  httpsPort: 443
  useSystemRoots: true
  k8sAuthMethodHost: ${kubernetes_api_endpoint}
connectInject:
  enabled: true
  metrics:
    defaultEnableMerging: true
  consulNamespaces:
    mirroringK8S: true  
meshGateway:
  enabled: true
  replicas: ${replicas}
ingressGateways:
  enabled: true
  defaults:
    replicas: ${replicas}
    service:
      type: LoadBalancer
      ports:
        - port: 80
  gateways:
    - name: ${cloud}-ingress-gateway
terminatingGateways:
  enabled: true
  defaults:
    replicas: ${replicas}
  gateways:
    - name: ${cloud}-terminating-gateway