alertmanager:
  enabled: false
nodeExporter:
  enabled: false
server:
  global:
    scrape_interval: 10s
pushgateway:
  enabled: false
extraScrapeConfigs: |
  - job_name: 'consul'
    metrics_path: "/v1/agent/metrics"
    params:
      format: ['prometheus']
    scheme: https
    tls_config:
       insecure_skip_verify: true
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app]
      regex: consul
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      regex: server|client
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex: 8501
      action: keep