output "eks_cluster_id" {
  description = "EKS cluster id"
  value       = module.eks.cluster_id
}

output "eks_cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "eks_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = module.eks.cluster_security_group_id
}

output "eks_kubectl_config" {
  description = "Kubernetes configuration generated by the module"
  value       = module.eks.kubeconfig
}

output "eks_config_map_aws_auth" {
  description = "Kubernetes configuration to authenticate to the EKS cluster"
  value       = module.eks.config_map_aws_auth
}

output "eks_workers_asg_arns_id" {
  description = "Id of the autoscaling groups containing workers"
  value       = module.eks.workers_asg_arns
}