---
apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: counting
spec:
  selector:
    app: counting
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: counting
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: counting
spec:
  protocol: tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counting
spec:
  replicas: 1
  selector:
    matchLabels:
      service: counting
      app: counting
  template:
    metadata:
      labels:
        service: counting
        app: counting
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      containers:
      - name: counting
        image: hashicorp/counting-service:0.0.2
        ports:
          - containerPort: 9001
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
      serviceAccountName: counting