---
apiVersion: v1
kind: Service
metadata:
  name: product-api-db
  labels:
    app: product-api-db
spec:
  selector:
    app: product-api-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api-db
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api-db
spec:
  protocol: tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-db
  labels:
    app: product-api-db
spec:
  replicas: 0
  selector:
    matchLabels:
      service: product-api-db
      app: product-api-db
  template:
    metadata:
      labels:
        service: product-api-db
        app: product-api-db
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      serviceAccountName: product-api-db
      containers:
        - name: product-api-db
          image: hashicorpdemoapp/product-api-db:v0.0.19
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: products
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          # only listen on loopback so only access is via connect proxy
          #args: ["-c", "listen_addresses=127.0.0.1"]
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - name: pgdata
          emptyDir: {}