output "vpc_id" {
  description = "VPC id"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "Private subnets"
  value       = module.vpc.private_subnets
}

output "cluster_id" {
  description = "EKS cluster id"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "Kubernetes configuration generated by the module"
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "Kubernetes configuration to authenticate to the EKS cluster"
  value       = module.eks.config_map_aws_auth
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster."
  value       = module.eks.cluster_iam_role_arn
}

output "workers_asg_arns_id" {
  description = "Id of the autoscaling groups containing workers"
  value       = module.eks.workers_asg_arns
}

output "private_nat_gateway_route_ids" {
  description = "Ids of the private nat gateway route."
  value       = module.vpc.private_nat_gateway_route_ids
}

output "public_internet_gateway_route_id" {
  description = "Id of the internet gateway route"
  value       = module.vpc.public_internet_gateway_route_id
}

output "private_route_table_association_ids" {
  description = "Ids of the private route table association"
  value       = module.vpc.private_route_table_association_ids
}

output "public_route_table_association_ids" {
  description = "Ids of the public route table association"
  value       = module.vpc.public_route_table_association_ids
}

output "public_fqdn_bastion_node" {
  description = "Public fqdn of bastion node"
  value       = aws_instance.bastion-node.public_dns
}

output "private_fqdn_cts_node" {
  description = "Private fqdn of CTS node"
  value       = aws_instance.cts-node.private_dns
}