output "vpc_id" {
  description = "VPC id"
  value       = module.vpc.vpc_id
}

output "private_subnets" {
  description = "Private subnets"
  value       = module.vpc.private_subnets
}

output "cluster_id" {
  description = "EKS cluster id"
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "Kubernetes configuration generated by the module"
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "Kubernetes configuration to authenticate to the EKS cluster"
  value       = module.eks.config_map_aws_auth
}

output "workers_asg_arns_id" {
  description = "Id of the autoscaling groups containing workers"
  value       = module.eks.workers_asg_arns
}